title: CringerLabs
subtitle: SysAdmin flying up to Cloud!
description: >- # this means to ignore newlines until "baseurl:"

url: "https://karlipegomes.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.jpeg
author: Karlipe Gomes
author_bio: Hi, my name is Carlos Felipe, better known as Karlipe. I am a RedHat fanboy, fan of Technology, passionate in Infrastructure and Cloud, and also a DJ in my spare time.
author_email: "karlipe@cringerlabs.com"
author_location: Brazil
author_website_url: "cringerlabs.com"
typewrite-text: SysAdmin flying up to Cloud!

author_work_experiences:
            - company_name: SEDUC-CE
              company_logo: seduc-ce.png
              company_url: https://seduc.ce.gov.br.com
              designation: Senior Infrastructure Engineer
              description: Working to support all applications to education public environment in State
              visibility: true
            - company_name: BeachPark
              company_logo: bpk.png
              company_url: https://www.beachpark.com.br
              designation: Infrastructure Team Lead
              description: Worked as Team Lead, managing Infrastructure as a Service to internal clients
              visibility: true
            - company_name: MobTelecom
              company_logo: mob.png
              company_url: https://www.mobtelecom.com.br
              designation: Solutions Architect
              description: Designing ways to solve problems clients using DataCenter Solutions
              visibility: true
            - company_name: CoreSec (EnergyTelecom Group)
              company_logo: coresec.png
              company_url: https://www.energytelecom.com.br
              designation: Red Hat Engineer
              description: Worked as Red Hat Partner deploying solutions to big Companies and Government
              visibility: true
            - company_name: EnergyTelecom
              company_logo: energy.png
              company_url: https://www.energytelecom.com.br
              designation: Technical Support Engineer
              description: Worked as Security Service Provider to big Companies and Government 
              visibility: true
            - company_name: MobTelecom
              company_logo: mob.png
              company_url: https://www.mobtelecom.com.br
              designation: Junior Support Analyst
              description: Worked managing Core and Client Servers/Storages, Virtualized and Bare-Metal
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: cringerlabs.png
                project_title: CringerLabs IaC
                project_description: A self Challenge to organize my principal products
                project_url: https://github.com/cringerlabs/lab-iac
                visibility: true

# social links
github_username:  cringerlabs
linkedin_username: cfgomes
telegram_username: karlipegomes

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: karlipegomes
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://cringerlabs.us10.list-manage.com/subscribe/post?u=dbccd98e032ae5f2751bbe133&amp;id=c177f31bb7

# formspree (contact form)
formspree_email: karlipe@cringerlabs.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# algolia search
algolia:
  application_id: NALF881FJV
  index_name: article # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 84c98d69ccc2e30f4ff778bd69b9c23d

# pagination of posts
paginate: 8
per_page: 8
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
